- lib/charms/tls_certificates_interface/v0/tls_certificates.py
- tests/charms/tls_certificates_interface/v0/test_tls_certificates.py
- tox.ini
This fixes linting and static analysis in PR #2 and also add a new tests. This is based on @delgod's PR. We need this functionality in charmed-magma to properly support scaling.
> All units should be able to receive certificates

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
The organisation (or department) is a mandatory field for MongoDB certificates.
> add possibility to set organisation

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- tests/charms/tls_certificates_interface/v1/test_tls_certificates_v1.py
- Fixes bug where charms with multiple units couldn't request certificates
- Improves code structure
- Reverts fix for ca chains being lists. This will be re-added later.
- Removes the broken "certificate revoked event". Those won't be able to exist since from the tls certificates requirer point of view, it is impossible to differentiate whether a certificate was revoked or wasn't yet created.
> [bug fix]: Fixes bug where charms with multiple units couldn't request certificates

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- tests/integration/v1/test_integration.py
- tests/unit/charms/tls_certificates_interface/v1/test_tls_certificates_v1_provides.py
- tests/unit/charms/tls_certificates_interface/v1/test_tls_certificates_v1_requires.py
- tox.ini
This PR adds a `revoke_all_certificates` method to `TLSCertificatesProvidesV1`. This is intended to be called by the provider charm when the root CA has changed.
> Add revoke_all_certificates to ProviderV1

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
Last PR was concurrent with another PR and they both specified the same patch version. The second PR changes were thus not published properly. This PR only bumps the LIBPATCH number to trigger a publication.
> Bump libpatch

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
sets LIBPATCH back to 1 because it was never published to charmhub.
Recent publish lead to this message from charmcraft:
```
Library charms.tls_certificates_interface.v2.tls_certificates has a wrong LIBPATCH number, it's too high and needs to be consecutive, Charmhub highest version is 2.0.
```
> sets LIBPATCH back to 1 because it was never published to charmhub

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
Charmcraft now supports the PYDEPS feature which pulls in libraries with pip automatically so users do not need to add them to requirements.txt.
(Is this really needed for this change?
> use pydeps

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_provides.py
Allows getting the issued certificates from the databags. Either by getting all certificates for all relations or getting certificates by relation ID.
The goal is to allow the provider charms to implement actions that list the issued certificates, addressing [this issue](https://github.com/canonical/self-signed-certificates-operator/issues/9).
> Adds methods to fetch certificates issued

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_provides.py
Adds a relation id parameter in get_requirer_csrs_with_no_certs
> Adds a relation id parameter in get_requirer_csrs_with_no_certs

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2.py
Add KeyUsage extension to generated CA certificates. This is required to follow `RFC 5280 Section 4.2.1.3` and fixes #71
> Add KeyUsage extension to generated CA certificates

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_certificates.py
Before this PR, `openssl verify` was failing for certs generated by the self-signed-certfiicates operator. For example:
- `verify error:num=21:unable to verify the first certificate`
- `error 85 at 0 depth lookup: Missing Authority Key Identifier`
- `verify error:num=30:authority and subject key identifier mismatch`
With the changes in this PR, verification passes (`10.43.8.206` is traefik's IP):
```
depth=1 C = US, CN = external.demo.ca
verify return:1
depth=0 CN = 10.43.8.206, x500UniqueIdentifier = 6e1b0143-392e-428b-87d7-5b240f9d90ee
verify return:1
DONE
test.crt: OK
```
Fixes #73.
- For the root CA, AKID=SKID (this is already implemented before this PR)
- For intermediate CAs and certs, the AKID must match the CA's SKID
For server certs, "CA" needs to be set to "FALSE".
Sample value: …
> Add more extensions

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_requires.py
It is possible for a certificate subject to not match its CSR and still be valid. For instance the country and orgs can be different. We now validate the modulus only when validating that a certificate matches a CSR. This change is necessary in order to fix this issue: https://github.com/canonical/manual-tls-certificates-operator/issues/77
- https://www.ssl.com/faqs/how-do-i-confirm-that-a-private-key-matches-a-csr-and-certificate/
> bugfix: Validates modulus in csr/cert comparison instead of subject

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_provides.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_requires.py
Implements option to request for a CA certificate. This PR should be kept in draft until the one in charm relation interface is merged: 
- https://github.com/canonical/charm-relation-interfaces/pull/118
> feat: Implements option to request a CA certificate

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_provides.py
- Uses relation ID when available
- Replaces `get_requirer_csrs_with_no_certs` with `get_outstanding_certificate_requests` and improves docstring content
> fix: Uses relation ID when available

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2.py
There was an issue in the `tls-certificates-interface` where TLS providers would crash when requires would set x.509 extensions in their CSR's that would be competing with extensions set by the provider. Now we simply ignore those competing extensions from the requirer and log this to inform the user.
This PR addresses the issue observed here:
- https://github.com/canonical/self-signed-certificates-operator/issues/52
> fix: logs instead of crashing when competing extensions

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
Looks like these were accidentally changed when creating version 2 of the tls-certificates-interface
> fix: Fix JSON schema IDs

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_requires.py
Added 2 new functions:
`get_assigned_certificates` gets all of the certificates that are available in the remote application databag.
`get_certificate_signing_requests` gets all of the generated certificate signing requests. It also provides the option to filter the csrs by wether they have their certificate available or not.
> feat: get_certificates and get_csrs

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tox.ini
pflake8 used to ignore the lib path for lint checks, here we run it in this path and we addresses the existing lint errors.
> chore: Add lint check to libs

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- pyproject.toml
`subject` was a parameter **and** a variable in the `generate_ca` function. Here we remove this redefinition and add the static check that will prevent this category of static errors from re-occuring in the future. 
```
lib/charms/tls_certificates_interface/v3/tls_certificates.py:710: error: Incompatible types in assignment (expression has type "Name", variable has type "str")  [assignment]
subject = issuer = x509.Name(
^
lib/charms/tls_certificates_interface/v3/tls_certificates.py:733: error: Argument 1 to "subject_name" of "CertificateBuilder" has incompatible type "str"; expected "Name"  [arg-type]
.subject_name(subject)
^~~~~~~
lib/charms/tls_certificates_interface/v2/tls_certificates.py:681: error: Incompatible types in assignment (expression has type "Name", variable has type "str") …
```
> chore: Add redefinition static check

- .github/workflows/main.yml
- charmcraft.yaml
The build process is currently failing on `main` at the `publish charm` stage because the charm doesn't build properly there. This PR uses `build-packages` to address this issue adds a CI step to build the charm making it less likely that we merge an un-buildable charm.
- CI failure: https://github.com/canonical/tls-certificates-interface/actions/runs/7995294620/job/21835286164
> fix: use build-packages in dummy charm

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
In cases where charms call public gets of the TLS Requirer and the tls relation was not created, the method would raise a Runtime error. Instead of that we now return an empty list since really, no cert has been assigned.
> fix: return empty list when get to TLS Requirer object given no tls relation

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
Could not change the name of the parameter altogether as that would have been a breaking/major change.
However we can improve the docstring making it clear to the user that subject here in fact is the Common Name that can be either an IP or a an FQDN
> chore: Enhances the documentation of the subject parameter generate_csr and generate_ca

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- pyproject.toml
- requirements.in
- requirements.txt
- tests/integration/v2/test_integration_v2.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_requires.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
Replace deprecated not_valid_after with not_valid_after_utc.
Fixes this issue:
- https://github.com/canonical/manual-tls-certificates-operator/issues/174
> fix: replace deprecated `not_valid_after` with `not_valid_after_utc`

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3.py
Adds the `chain_as_pem()` method to `CertificateAvailableEvent` and `ProviderCertificate` to enable users to easily get the full chain as a single PEM file.
> feat: Add chain_as_pem method to CertificateAvailableEvent and ProviderCertificate

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
We now fail quickly when using the lib with versions of Juju that do not support secrets. We also better document the fact that v3 of the lib only works with Juju >= 3.0.
> fix: fail quickly when lib v3 is used with an unsuported Juju version

- .github/workflows/main.yml
Adds on pull_request event as a trigger of the CI, this is important so PRs created from forks can trigger the CI.
> fix: Adds on pull_request event as a trigger of the CI

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
PR #150 caused unit tests in every tls requirer to crash because there is no "harness" way to mention that the tests should be executed with Juju 3. This change here relaxes the behavior introduced in that PR to simply log a warning instead.
- Matrix discussion: https://matrix.to/#/!xdClnUGkurzjxqiQcN:ubuntu.com/$9PU1wxgNUzzYKC1wL-OjfAPErt1BUJM0GmGMVrDCfAY?via=ubuntu.com&via=matrix.org&via=fsfe.org
- PR Failure: https://github.com/canonical/tls-certificates-requirer-operator/pull/87
> fix: log warning instead of crashing when using with wrong juju version

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
Explicitly state in documentation that the tls lib requires charms to build with cryptography >= 42.0.0 (because we use `not_valid_after_utc`).
Fixes #148 
- https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.not_valid_after_utc
> docs: require cryptography >= 42.0.0

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/integration/v3/requirer_charm/src/charm.py
Uses RelationCreatedEvent instead of RelationJoinedEvent in the example requirer in the docstring.
Fixes #144
> fix: Uses RelationCreatedEvent instead of RelationJoinedEvent in the example requirer in the docstring

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
As the [bug](https://bugs.launchpad.net/juju/+bug/2058012) we opened in Juju for secret creation issues has not been addressed yet, there was a suggestion to log the csr so when the issue comes up again we might know if it was because of the label using that csr.
> fix: Adds a debug log for creating secret with CSR as a label

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
Adding more logs to debug [2058012](https://bugs.launchpad.net/juju/+bug/2058012)
Running the [CI a few times with these changes in Vault](https://github.com/canonical/vault-k8s-operator/pull/369) didn't result in the error coming up, so it could be useful to have these logs in more runs.
> fix: Adds more logs when creating secrets

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
Fixes #139 
We replace the usage of CSRs as secret labels with the hexadecimal representation of their sha256 hash.
The goal is to avoid having special characters in the secret label.
> chore: Uses the hash of the CSR as a secret label

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3.py
This error comes from the us not handling the fact that elliptic curve keys do not have the `n` property at all. For the most part, it seems to be enough to skip the second check and just compare the public bytes only. 
Fixes [#249](https://github.com/canonical/manual-tls-certificates-operator/issues/249) (in a different repo)
> fix: csr_match_check breaks on ec private keys

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3.py
We assumed that the IP address received for the sans_ip was an IPv4 address. This caused an where the CSR could not be generated on systems with IPv6 addresses.  
Fixes #194 
```
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-openstack-hypervisor-0/charm/./src/charm.py", line 565, in <module>
main(HypervisorOperatorCharm)
File "/var/lib/juju/agents/unit-openstack-hypervisor-0/charm/venv/ops/main.py", line 544, in main
manager.run()
File "/var/lib/juju/agents/unit-openstack-hypervisor-0/charm/venv/ops/main.py", line 520, in run
self._emit()
File "/var/lib/juju/agents/unit-openstack-hypervisor-0/charm/venv/ops/main.py", line 509, in _emit
_emit_charm_event(self.charm, self.dispatcher.event_name)
File "/var/lib/juju/agents/unit-openstack-hypervisor-0/charm/venv/ops/main.py …
```
> fix: support IPv6 address in CSR sans ip

- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3.py
There is no guarantee that `get_values_for_type` would return that IP addresses in the same ordered as we inserted them in the certificate. This caused intermittent unit tests failures. Here we check that the value is there, regardless of its position.
Example error:
- https://github.com/canonical/tls-certificates-interface/actions/runs/9719546497/job/26829538680?pr=197#step:4:344
> fix: ignore order of IP addresses in unit test

- .github/workflows/main.yml
Propagating this change from times long ago: https://github.com/canonical/vault-operator/pull/85
There's no need to trigger on every push and pull_requests that merge to master, because we end up with duplicate runs on every PR.
This change will cause it to:
- Run on every change to a PR that merges to main (covered by the pull_request trigger) so that devs can validate their code works.
- Run on every commit that is merged into main (covered by the new restrictions on the push trigger) so that we validate the code still works once it is pushed, and publish things accordingly.
> build: Restrict the push trigger to the main branch

- requirements.in
- requirements.txt
Reverts canonical/tls-certificates-interface#212
The PR that is being reverted was created and merged by dependabot. It was merged despite the CI failure as the build step was not added to the list of expected checks in the branch rules.
> fix: Revert "chore: bump rpds-py from 0.18.0 to 0.19.1 in the pip_dependencies group"

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/integration/v4/provider_charm/requirements.in
- tests/integration/v4/provider_charm/requirements.txt
- tests/integration/v4/provider_charm/src/charm.py
- tests/integration/v4/requirer_charm/src/charm.py
- tests/integration/v4/test_integration_v4.py
- tests/unit/charms/tls_certificates_interface/v4/certificates.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_provider_charm/charmcraft.yaml
- tests/unit/charms/tls_certificates_interface/v4/dummy_provider_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_provides.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
Implement the provider side of the TLS certificates library V4.
In our TLS Providers we heavily rely on getters (instead of the TLS custom events) to get the outstanding certificate requests and other tls related information. Because of this, we completely remove custom events from the tls lib v4. 
Just like we did for the requirer side, we use Pydantic for relation data validation instead of json schemas. 
Just like we did for the requirer side, here we use scenario instead of harness for unit testing.
There were a couple of helper methods here that were used only by self signed certificates and those have been removed and will be added in the self-signed-certificates charm instead:
- generate_certificate
- generate_ca
> feat: implement provider side of tls certificates v4

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
We prevent from reading/dumping to relation data when using the app mode.
```
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-requirer-appl-1/charm/venv/ops/model.py", line 3187, in _run
result = subprocess.run(args, **kwargs)  # type: ignore
File "/usr/lib/python3.10/subprocess.py", line 526, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-requirer-appl-1/relation-get', '-r', '2', '-', 'requirer-appl', '--app', '--format=json')' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-requirer-appl-1/charm/./src/charm.py", line 408, in <module>
main(TLSRequirerCharm)
File …
```
> fix: do not load/dump when non leader in app mode

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/integration/v4/requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
There currently is an issue in v4 of the lib where two CertificateSigningRequest objects that have the same `sans_dns` but in different orders wouldn't be considered to be equal. Here we fix this issue by using frozensets instead of tuples for representing `sans`.
```python
a = CertificateRequest(common_name='tls-requirer-unit-2.test-integration-awm9', sans_dns=('example.org', 'example.com'), sans_ip=None, sans_oid=None, email_address=None, organization='Canonical', organizational_unit=None, country_name='GB', state_or_province_name='London', locality_name='London', is_ca=False)
b = CertificateRequest(common_name='tls-requirer-unit-2.test-integration-awm9', sans_dns=('example.com', 'example.org'), sans_ip=None, sans_oid=None, email_address=None, organization='Canonical', …
```
> fix: use frozenset to represent sans

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
`get_provider_certificate` is used inside of the LEGO K8s library and should be public.
- https://github.com/canonical/lego-base-k8s-operator/pull/162
> fix: move get_provider_certificate to public

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
Here we add the same certificate helpers we had in previous versions of the lib:
- generate_private_key
- generate_csr
- generate_ca
- generate_certificate
The use of those helpers can be separated in 3 categories:
- In charm code of TLS requirers (when the charm is not integrated with a TLS provider and we want to generate self signed certs instead).
- In unit tests of TLS requirers
- In the self-signed certificates charm
If we do not include those here in the lib, many charms will create their own implementation. The rationale here is to centralise those helper methods in 1 place.
> feat: add public certificate helpers

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
This change fixes a small mistake in the docs of the return type of the generate_private_key function.
> fix: small doc error

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/certificates.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_provider_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/charmcraft.yaml
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
Fix an issue where requests for CA certificates were not managed correctly. The CertificateRequest was made for a CA certificate, the lib would create the correct CSR, then would remove the CSR from the relation databag thinking it's not a match.
Here we get rid of the `CSR.to_certificate_request` and replace it with the `CertificateRequest.from_csr`. Since this library is still in beta, we don't go with a major version bump.
> fix: allow ca certificate requests

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
Fixes #228.
Adds a workaround function that would try to get the csr from the secret content and if it isn't there it would attempt to get it from the secret label as the lib was doing till version 3.14
> fix: Backward compatibility issue with getting the CSR from Juju secret

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_provides.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_provider_charm/charmcraft.yaml
- tests/unit/charms/tls_certificates_interface/v4/dummy_provider_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_provides.py
Add a `get_unsolicited_certificates` method for the provider side of the TLS certificates interface.
This method is needed in TLS constraints (in this PR):
- https://github.com/canonical/tls-constraints-operator/pull/114
> feat: add get_unsolicited_certificates to TLS provider class

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
While troubleshooting an issue with certificate expiry, I struggled understanding the `calculate_expiry_notification_time`, mainly because of the name of variables and their docstring. Here we use the more commonly used `not_valid_before` and `not_valid_after` variable names instead.
We also remove the word `hours` as those could be minutes/years, it does not matter.
There is no change in the actual behavior.
> chore: improve variable naming for computing certificate expiry

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/charmcraft.yaml
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
This PR allows requirer charms to ask for their certificates to be renewed before those actually expire.
This was required for [this](https://github.com/canonical/vault-k8s-operator/issues/500) fix in Vault.
> feat: Adds a function to allow certificate renewal

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
When a relation to a certificate provider is created:
- `relation-joined` runs
- The requirer sends its request (V3)
- `relation-changed` runs for the provider and the certificate is provided --> certificate secret is created
- `relation-changed` runs again and the secret is updated without an actual change of its content, but a new revision is created.
-  Time passes and `secret-expired` runs for both revisions, the code removes all revisions when the first event and it will fail to get the content of the secret when it handles the second one.
- `SecretNotFoundError` is raised
To fix the issue:
- New revision should not be created if secret content is not changed
- We should handle the possible `SecretNotFoundError` when running `get_content`
This PR:
- Fixes #228 
- Adds tests
> fix: Fixes certificate secret management

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
Bug:
While iterating over certificates we return if a secret was already created for one of them which will make us ignore the rest of the certificates. We continue instead.
> fix: Use continue instead of return in loop

- .github/workflows/main.yml
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
When a new secret revision is created and all parties observing the secret refresh the revision they track to the latest one, juju will emit the SecretRemoveEvent to signal to the charm that the old revision can be removed.
We remove it to avoid the following scenario:
- The provider shares a new certificate before the expiry of the current one.
- The requirer creates a new secret revision where the new cert is stored.
- The current cert expires before the new one.
- The current cert expiry is triggered.
- The new certificate is removed because of the `remove_all_revisions` call when handling secret expiry.
- A new certificate is requested for no good reason.
Although it isn't that critical it should lead to a more predictable certificate life cycle.
> feat: Removes old certificate secret revisions

- .github/workflows/main.yml
- Bump Juju to `3.6/stable`
- Bump lxd to `5.21/stable`
- Bump MicroK8s to `1.31-strict/stable`
> chore: bump juju, lxd, and microk8s versions in CI

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/integration/v4/requirer_charm/requirements.txt
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
On the Requirer side of this interface, when charms request to know their assigned certificates (ex. using the `get_assigned_certificates` method), any certificate provided through the relation would be returned, even if that certificate does not match the requirer's private key. In order to ensure that bad certificates (ex. if the TLS provider gets corrupted) don't make their way into the TLS requirer workload, here we add a validation to ensure that the provided certificate matches with the requirer's private key. 
This security improvement came in as a request from the data platform team.
Fixes #283
> chore: add validation to ensure provided certificate matches private key

- pyproject.toml
Here we use python 3.8 for static checks. Check failures will mean that our library code is not compatible with Python 3.8. 
This ensures that our lib keeps on being usable on charms built on Ubuntu 20.04. Without this check, it is easy to introduce new syntax without realizing that we're breaking 20.04 charms (ex. with the `|` character in return types). 
Check failures will look like:
```
(venv) guillaume@courge:~/code/tls-certificates-interface$ tox -e static
static: commands[0]> pyright /home/guillaume/code/tls-certificates-interface/src/ /home/guillaume/code/tls-certificates-interface/tests/unit/ /home/guillaume/code/tls-certificates-interface/tests/integration/ /home/guillaume/code/tls-certificates-interface/lib/
/home/guillaume/code/tls-certificates-interface/lib/charms/tls_certific …
```
> chore: use python 3.8 for static checks

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- pyproject.toml
- src/charm.py
- tests/integration/v2/provider_charm/src/charm.py
- tests/integration/v2/requirer_charm/src/charm.py
- tests/integration/v2/test_integration_v2.py
- tests/integration/v3/provider_charm/src/charm.py
- tests/integration/v3/requirer_charm/src/charm.py
- tests/integration/v3/test_integration_v3.py
- tests/integration/v4/provider_charm/src/charm.py
- tests/integration/v4/requirer_charm/src/charm.py
- tests/integration/v4/test_integration_v4.py
- tests/unit/charms/tls_certificates_interface/v2/dummy_provider_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v2/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_provides.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_requires.py
- tests/unit/charms/tls_certificates_interface/v3/dummy_provider_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v3/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_provides.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_provider_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
This change adds a pyright check to ensure that we add type hints to our code
> build: Enable pyright to check if type hints are missing

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
Hello team,
When trying to rotate the certificates by setting the private key manually in the etcd charm, I noticed a bug in the ops framework that caused the TLS lib to fail to load the newly updated private key in the same hook.
As shown in this [proof-charm](https://github.com/skourta/juju-update-secret-issue) running the `rotate-private-key` action will update the private key but the value read after the regeneration is still the old one.
```python
def _on_rotate_private_key(self, event: ops.ActionEvent) -> None:
old_value = self.certificates.private_key
self.certificates._regenerate_private_key()
new_value = self.certificates.private_key
event.set_results(
{
"old-value": old_value,
"new-value": new_value,
"z-key-rotated": old_value != new_value,
}
)
```
This is due to a bug in the …
> fix: writing secret content bug from ops

- .github/workflows/main.yml
- pyproject.toml
- tests/integration/v4/conftest.py
- tests/integration/v4/provider_charm/charmcraft.yaml
- tests/integration/v4/provider_charm/src/charm.py
- tests/integration/v4/requirer_charm/charmcraft.yaml
- tests/integration/v4/requirer_charm/src/charm.py
- tests/integration/v4/test_integration_v4.py
Adds an integration test to deploy the the provider and requirer charms with the latest published lib first, request a certificate, then refresh the charm with the latest revision and renew the certificate.
This will hopefully catch issues with upgrading between revisions.
> test: Test upgrade path

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_provides.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
Fixes #302 
~~Makes sure that the mode chosen by requirer (Unit or APP) is respected.~~
- This PR adds a test to ensure that the csrs are added to the correct databags depending on Mode.
- Allows the relation databag to be empty without failing validation (This will reduce the number of log entries with validation failures)
> chore: Add tests to make sure mode is respected

- .github/workflows/upload.yml
The charm and libraries currently fail to publish after an update to the version of Ubuntu used on the runners. This is due to charmcraft running in destructive mode and directly using the runner to pack the charm, instead of using LXD.
This disables destructive mode, forcing charmcraft to use LXD and not depend directly on the runner's OS version.
> fix: Do not use destructive mode on upload to use LXD

- tests/integration/v4/test_integration_v4.py
- uv.lock
I'm unsure why, but [uv seems to be complaining that the dependencies need to be re-locked](https://github.com/canonical/tls-certificates-interface/pull/325).
However, upon running `uv lock`, a new version of `pyright` was pulled in which seems to change the results of static analysis.
Specifically, it is complaining that we're ignoring the (inferred) return value of `None` in the python-libjuju 2.9 dependency (newer versions have type hints, and don't cause the issue).
So, this PR includes the `uv lock` changes, plus some ignores to make pyright happy.
> build: update lock file

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
Ensure the secret that should contain the secret revision exists before trying to remove it, otherwise the unit could be stuck in an error state. 
See https://github.com/juju/juju/issues/19036 for more information.
Fixes the build for https://github.com/canonical/vault-k8s-operator/pull/552
~~Requires #326~~
> fix: Ensure secret exists before removal to prevent error state

- .github/renovate.json5
This is an attempt (I don't really know how to test this other than to merge and see if it works) to prevent renovate from updating the version of `python-libjuju` otherwise it will keep coming back: https://github.com/canonical/tls-certificates-interface/pull/323, https://github.com/canonical/tls-certificates-interface/pull/320
These versions of `python-libjuju` are explicitly set so that we can test different versions of Juju. We do not want the latest version.
~~Requires #326~~
> build: Disable major version updates for juju to prevent breaking integration tests

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
The `from_string` function in the `CertificateSigningRequest` class creates an object from a csr string, the function currently does not extract the organizational_unit from the string and doesn't convert the sans_oid from `FrozenSet[ObjectIdentifier]` to `FrozenSet[str]` correctly. This PR fixes those issues.
> fix: Fixes from_string in CertificateSigningRequest

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
`add_unique_id_to_subject_name` is currently always set to True in the `generate_csr` function, this PR allows the requirer to decided its value.
> feat: Allows the requirer to set the value of add_unique_id_to_subject_name in the CertificateRequestAttributes

- .github/workflows/main.yml
- pyproject.toml
- tests/integration/v2/conftest.py
- tests/integration/v2/test_integration_v2.py
- tox.ini
- uv.lock
Use `jubilant` instead of `pytest-operator` for the integration tests of v2.
This is done now to remove the conflicting dependencies on `juju==2.9.49.1` and `juju>3` that break Renovate. This will help ensure that regular updates on our dependencies keep happening automatically.
> chore: Use Jubilant for v2 integration tests

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- pyproject.toml
- tests/unit/certificate_validation.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
- uv.lock
Fixes https://github.com/canonical/self-signed-certificates-operator/issues/330
This should prevent us from accidentally violating RFC 5280 such as in https://github.com/canonical/tls-certificates-interface/pull/336, where it wasn't obvious what the rules around KeyUsage were.
Supercedes #333 
Uses [pkilint](https://github.com/digicert/pkilint) to validate that the certificates we generate in the tests are well formed (no errors, and follow best practices according to RFC 5280).
To satisfy some of the rules
- we must include the e-mail address in the SAN extension of the certificate if the e-mail is present (it should be included in both).
- we must not add the SAN extension if it is empty
> test: Validate certificates in tests

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4_requires.py
Fixes #355 
Currently the requirer charm relies on a refresh event to update the certificate request attributes. In this PR we provide a public `sync` function that will allow the requirer to call it and directly run `_configure` so csrs are synced without waiting for the refresh event.
> feat: Adds sync public function to enable requirer charms to run _configure
