canonical/tls-certificates-interface

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- tests/charms/tls_certificates_interface/v1/test_tls_certificates_v1.py
Uses the most recent version of the json schema (CA chains are lists of strings)
> Bugfix: Uses the most recent version of the json schema (CA chains are lists of strings)

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- tests/charms/tls_certificates_interface/v1/test_tls_certificates_v1.py
CA chains are list of strings instead of strings.
> CA chains are list of strings instead of strings

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- tests/charms/tls_certificates_interface/v1/test_tls_certificates_v1_provides.py
Provider can provide certificates to multiple apps. Closes #16
> Provider can provide certificates to multiple apps

- .github/pull_request_template.md
Adds lib check to PR template.
> Adds lib check to pr template

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
Re-apply of https://github.com/canonical/tls-certificates-operator/pull/32
> chore: drop noisy update_status warnings to debug

- renovate.json
> [Chore] Adds renovate to the project

- CODEOWNERS
Adds @canonical/telco as code owner of the project.
> [Chore] Adds @canonical/telco as code owner of the project

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
Adds safeguard in relation broken events. This PR fixes #45 .
Note: I was unable to find a way to test this behavior with harness, @sed-i do you know if that's doable?
> [Bug fix] Adds safeguard in relation broken events

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
1. Uses %s string formatting instead of f-strings in logging
2. Removes relation data content from logs.
> [Feat] Improves logging

- charmcraft.yaml
This change fixes the charm not packing locally, and should hopefully fix the broken CI.
> Fix charm packing for CI

- .github/workflows/upload.yml
- charmcraft.yaml
Run upload workflow on all changes. Otherwise, it will not run on a documentation change or when fixing bugs outside of the lib file.
> Run upload workflow on all changes

- docs/index.md
- metadata.yaml
Adding documentation to Charmhub for tls-certificate-interface library placeholder charm.
> Add documentation to Charmhub

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_provides.py
Adds functions to the provider to fetch csrs of the requirer units.
> Adds functions to the provider to fetch csrs

- metadata.yaml
Add a github link to charmhub.
Note: I think the above checks are probably not required for this change.
> Add a github link to charmhub

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
List elements should not be removed while iterating over the list as that can cause issues with the loop. This change uses a copy of the list instead of deleting elements from the list that we are iterating over.
> Fixes bug in get_requirer_csrs_with_no_certs

- lib/charms/tls_certificates_interface/v0/tls_certificates.py
- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
Uses narrower ignore statement to fix static analysis issues as seen in PR #78
> chore: Uses narrower ignore statement

- .github/workflows/lint-pr.yaml
Uses semantic PR title validation
> chore: Uses semantic PR title validation

- tox.ini
Fixes https://github.com/canonical/tls-certificates-interface/issues/85.
- Updates Libjuju version to 3.2.2 to make it compatible with 3.1/stable. 
- Fixes the asyncio loop depreciation issue which appears with Python 3.11.
Reference: https://discourse.charmhub.io/t/pylibjuju-3-2-2-0-release-notes/11798
> fix: Update libjuju version to make it compatible with 3.1/stable

- .github/workflows/main.yml
bump juju version from 3.1 to 3.4.
> chore: bump juju to 3.4

- .github/workflows/main.yml
> chore: bump microk8s to v1.29

- .github/workflows/dependabot_pr.yaml
- .github/workflows/main.yml
- pyproject.toml
- tests/integration/v2/provider_charm/src/charm.py
- tests/integration/v2/provider_charm/src/self_signed_certificates.py
- tests/integration/v2/requirer_charm/src/charm.py
- tests/integration/v3/provider_charm/src/charm.py
- tests/integration/v3/provider_charm/src/self_signed_certificates.py
- tests/integration/v3/requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_provides.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2_requires.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_provides.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3_requires.py
- tox.ini
- Automates dependabot PR review and merge
- Adds concurrency job to cancel currently running CI actions when a new commit is pushed on the same branch. (Excludes main from this logic)
> feat: Automates dependabot PR review and merge

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v3/test_tls_certificates_v3.py
Add the option to request for certs for a certain locality. This includes:
- Country name (already supported)
- State or Province Name (new)
- Locality name (new)
> feat: add localisation options in csr

- lib/charms/tls_certificates_interface/v0/tls_certificates.py
- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- pyproject.toml
- tests/integration/v2/requirer_charm/src/charm.py
- tests/integration/v3/requirer_charm/src/charm.py
- tests/unit/charms/tls_certificates_interface/v2/test_tls_certificates_v2.py
- tox.ini
Fix linting issues and adapt project settings to make sure we catch them in the future.
Fixes #50
> chore: fix linting issues

- .github/workflows/upload.yml
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/test_tls_certificates_v4.py
- Resets libpatch to 0
- Cleans up some unused code in the lib
- Adds the publish workflow
- Improves the documentation (We rely on the documentation on charmhub on how to use the lib, here we makes sure to add the expected dependencies"
- validity times of a `ProviderCertificate` should not be optional they are made mandatory.
> chore: Cleans up the lib and prepares it for publishing

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
Fixed breaking change, by adding back older python support.
> fix: use union instead of OR

- pyproject.toml
- tests/integration/v2/requirer_charm/src/charm.py
- tests/integration/v3/requirer_charm/src/charm.py
Checks for some common logging patterns to avoid.
> build: Add logging lint checks to ruff

- .github/workflows/main.yml
Use shared workflows from https://github.com/canonical/identity-credentials-workflows instead of repeating the same workflows in each project.
This is a first step, and only includes the workflows that were trivial to migrate. More complex workflows that would require parameterization have not been migrated.
> build: Use shared workflows

- charmcraft.yaml
- pyproject.toml
- tox.ini
- uv.lock
> chore: Bump dependencies

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
Improve explanation of how UNIT and APP modes are used
> docs: Improve explanation of how UNIT and APP modes are used

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/charms/tls_certificates_interface/v4/dummy_provider_charm/src/charm.py
- uv.lock
Update dependencies and fix some static errors that appeared.
Breaking this out to keep another PR smaller.
> chore: Update dependencies

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
> fix: bump versions of libs

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- Make it clear when a request and a certificate don't match because of the `is_ca` field
- Make sure the latest revision of the pk secret is fetched within the same hook
> fix: Improves logging and make sure latest revision of private key secret is followed within same hook
